version: 2.1
jobs:
  build:
    docker: 
      - image: "debian:bullseye"
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Installing build tools and deps
          command: 'utility/install-linux-tools.sh'
      - run:
          name: Build CMAKE project
          command: 'mkdir build && cd build && ls .. && cmake ..' 
      - run:
          name: Build binaries
          command: 'cd build && make'
      - run:
          name: run vol tests
          command: 'cd build && src/test/vol-tests'

